### PR TITLE
Ruby 3

### PR DESCRIPTION
**Pull request by jage**
* [x] Ruby 3
* [ ] Sentry Ruby
* [ ] Latest rubocop (or should we switch no another lint?)

### CODE REVIEW

**Comment by jage** [comment]
Running the specs prints this, pretty sure it's from Puma https://cs.github.com/puma/puma/blob/914a0022cc10e566141096ad8599f5ef5114c0b6/lib/puma/request.rb#L449

```
2022-05-27 20:58:49 +0200 Read: #<NoMethodError: undefined method `each' for nil:NilClass

      headers.each do |k, vs|
             ^^^^^>
```

**Comment by dentarg** [comment]
> Latest rubocop 

We have that now with https://github.com/Starkast/wikimum/pull/339

> (or should we switch no another lint?)

We can always try other things, be as a separate PR/issue?

**Comment by dentarg** [comment]
I think we should do the `sentry-raven` -> `sentry-ruby` migration separate from updating to Ruby 3. We should do it first (I guess you added it because `sentry-raven` hasn't been tested well with Ruby 3.1?

**Comment by dentarg** [comment]
> Running the specs prints this, pretty sure it's from Puma

I suspect we have faulty specs

**Comment by jage** [comment]
> I think we should do the `sentry-raven` -> `sentry-ruby` migration separate from updating to Ruby 3. We should do it first (I guess you added it because `sentry-raven` hasn't been tested well with Ruby 3.1?)

Yes, don't want to run sentry-raven with Ruby 3.

**Comment by jage** [comment]
Let's do a new branch on the a new Ruby 3 attempt.

**Pull request closed without merging**
