### PR TITLE
Remove the New Relic agent

### PR DESCRIPTION
**Pull request by dentarg**
We don't use it much I think, and makes the app a bit more privacy minded.

### CODE REVIEW

**Comment by dentarg** [comment]
Seems like we are running into https://github.com/travis-ci/travis-ci/issues/8969

**Comment by jage** [comment]
> We don't use it much I think, and makes the app a bit more privacy minded.

FYI I'd like to remove Google Analytics as well.

**Comment by dentarg** [comment]
> continuous-integration/travis-ci/push — The Travis CI build is in progress

Was running without doing anything for over 7 minutes, restarted it manually...

**Comment by dentarg** [comment]
> Ran for 10 min 4 sec

Restarting it again...

**Comment by dentarg** [comment]
Forgot to remove the addon, did that now:

```
$ heroku addons:destroy --app=wikimum --confirm=wikimum NEW_RELIC
Destroying gazing-nimbly-3519 on ⬢ wikimum... done
```

**Pull request merged**
