### PR TITLE
Ruby 2.5, security updates, integration test

### PR DESCRIPTION
**Pull request by dentarg**

### CODE REVIEW

**Comment by dentarg** [comment]
Hmm, what's Tidelift?

**Comment by dentarg** [comment]
> Hmm, what's Tidelift?

Under "Webhooks" we have this one

> `https://hooks.dependencyci.com/events  (pull_request and push)`

dependencyci.com redirects to tidelift.com

https://tidelift.com/repo/github/Starkast/wikimum/builds/17

**Comment by jage** [comment]
> Hmm, what's Tidelift?

Yeah, Dependency CI + Libraries.io merged with Tidelift.

> Today we have some pretty big news. Ben and I are joining Tidelift, a new company focused on making open source software work better for developers and users, and we’re bringing Libraries.io and Dependency CI into the fold as well. For more details check out the Tidelift blog post and Ben’s blog post.

https://medium.com/libraries-io/why-libraries-io-and-dependency-ci-are-joining-tidelift-1caf72f4d1b0

---

I haven't looked if there's any changes to the service. I think we can remove this since GitHub has added a the dependency graph.

**Comment by dentarg** [comment]
I think we can keep Tidelift, seems pretty nice. I can make it green later in another pull request.

**Comment by jage** [comment]
I think this looks good, but I'd like to update a few more gems to avoid warnings and hopefully ensure better stability with Ruby 2.5. See #71 (PR against this branch)

**Comment by jage** [comment]
I don't think this was deployed since the CIs don't approve.

**Comment by dentarg** [comment]
Oh, good catch

**Pull request merged**
